name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        make
        mv token token-manager-amd64
        echo "Darwin build"
        make build_osx
        mv token token-manager-darwin
        echo "Power8 build"
        make build_power8
        mv token token-manager-power8
        echo "ARM64 build"
        make build_arm64
        mv token token-manager-arm64
        echo "Windows build"
        make build_windows
        mv token token-manager-windows

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binary
      id: upload-auth-proxy-server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./auth-proxy-tools.tar.gz
        asset_name: auth-proxy-tools.tar.gz
        asset_content_type: application/octet-stream

    - name: Upload darwin binary
      id: upload-auth-proxy-server-darwin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./auth-proxy-tools_darwin.tar.gz
        asset_name: auth-proxy-tools_darwin.tar.gz
        asset_content_type: application/octet-stream

    - name: Upload power8 binary
      id: upload-auth-proxy-server-power8
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./auth-proxy-tools_power8.tar.gz
        asset_name: auth-proxy-tools_power8.tar.gz
        asset_content_type: application/octet-stream

    - name: Upload arm64 binary
      id: upload-auth-proxy-server-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./auth-proxy-tools_arm64.tar.gz
        asset_name: auth-proxy-tools_arm64.tar.gz
        asset_content_type: application/octet-stream

    - name: Upload windows binary
      id: upload-auth-proxy-server-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./auth-proxy-tools_windows.tar.gz
        asset_name: auth-proxy-tools_windows.tar.gz
        asset_content_type: application/octet-stream
